name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      # Skip installing requirements.txt since it's missing

      - name: Install flake8
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest
